config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  get "/auth/twitter/callback", to: "fetchr_social#connect"
  get "/auth/failure", to: "fetchr_social#failure"

  scope module: :adapters do
    resource :redbooth_settings, only: [:edit, :update]
    get "/auth/redbooth/callback", to: "redbooth_settings#connect"
  end
  post "fetchr/start", to: "fetchr_status#start", as: "start_fetchr"
  post(
    "fetchr/import_and_start",
    to: "fetchr_status#import_and_start",
    as: "import_and_start_fetchr"
  )
  get "reset", to: "reset#reset", as: :reset
  root to: "fetchr_status#show"
end

app/models/adapters/redbooth_settings.rb
module Adapters
  class RedboothSettings
    include ActiveModel::Model

    attr_accessor :project_id, :task_list_id, :task_private,
                  :task_description, :token, :refresh_token, :key, :secret

    def self.fetch
      new(SocialPostr::Adapters::SettingsRepository.fetch(:redbooth))
    end

    def save
      SocialPostr::Adapters::SettingsRepository.save(:redbooth, attributes)
    end

    def attributes
      {
        key:           ENV["REDBOOTH_KEY"],
        secret:        ENV["REDBOOTH_SECRET"],
        token:         token,
        refresh_token: refresh_token,
        project_id:    project_id,
        task_list_id:  task_list_id,
        task_private:  task_private,
        task_description: task_description.present? ? task_description : nil
      }
    end
  end
end

app/models/fetchr_social_settings.rb
class FetchrSocialSettings
  include ActiveModel::Model
  DB_KEY = :social_fetchr_settings
  FETCHR_KEYS = [:app_key, :app_secret, :client_key, :client_secret]
  attr_accessor :client_key, :client_secret, :name
  validates :client_key, :client_secret, presence: true

  def self.fetch
    db_client.hgetall(DB_KEY).symbolize_keys
  end

  def self.satisfied?
    fetch.values_at(*FETCHR_KEYS).all?
  end

  def save
    return false unless valid?
    self.class.db_client.mapped_hmset(DB_KEY, attributes)
    true
  end

  def self.for_fetchr
    fetch.slice(*FETCHR_KEYS)
  end

  private

  def attributes
    {
      app_key: ENV["TWITTER_KEY"],
      app_secret: ENV["TWITTER_SECRET"],
      client_key: client_key,
      client_secret: client_secret,
      name: name
    }
  end

  def self.db_client
    $redis
  end
end

app/controllers/adapters/redbooth_settings_controller.rb
module Adapters
  class RedboothSettingsController < ApplicationController
    def edit
      @settings = RedboothSettingsPresenter.decorated_settings
      # omg network request in the controller!
      # I could cache the task list initialy when getting oauth token,
      # but this will not update automatically when new task lists are created
      # The best way is to make an async-request from the client,
      # but the current timebox limited me from doing so
      @task_lists = RedboothTaskListRetriever.fetch_task_lists(@settings.token)
    rescue
      flash[:error] = "Could not connect to Redboot. Please update the token"
      redirect_to :root
    end

    def update
      RedboothSettingsRepository.update(params[:adapters_redbooth_settings])
      redirect_to :root
    end

    def connect
      credentials = request.env["omniauth.auth"]["credentials"]

      RedboothSettingsRepository.update_tokens(
        token: credentials["token"],
        refresh_token: credentials["refresh_token"]
      )

      redirect_to :root
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fetchr_social_controller.rb
class FetchrSocialController < ApplicationController
  def connect
    settings = {
      name: request.env["omniauth.auth"][:info][:nickname],
      client_key: request.env["omniauth.auth"][:credentials][:token],
      client_secret: request.env["omniauth.auth"][:credentials][:secret]
    }
    FetchrSocialSettings.new(settings).save
    redirect_to :root
  end

  def failure
    flash[:error] = "#{params[:strategy].titleize} Connection Failed"
    redirect_to :root
  end
end

app/controllers/fetchr_status_controller.rb
class FetchrStatusController < ApplicationController
  def show
    @manager = FetchrStatusDecorator
  end

  def start
    SocialFetchr.check_and_process_updates(
      credentials: FetchrSocialSettings.for_fetchr,
      async: true
    )
    redirect_to :root
  end

  def import_and_start
    SocialFetchr.process_all(
      credentials: FetchrSocialSettings.for_fetchr,
      async: true
    )
    redirect_to :root
  end
end

app/controllers/reset_controller.rb
require "sidekiq/api"
class ResetController < ApplicationController
  def reset
    Sidekiq::Queue.new.clear
    Sidekiq::Queue.new(SocialFetchr::Workers::Importer::QUEUE).clear
    Sidekiq::ScheduledSet.new.clear
    redis = $redis
    redis.del(:postr_redbooth_settings)
    redis.del(FetchrSocialSettings::DB_KEY)

    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/adapters/redbooth_settings/edit.html.erb
<h1>Edit Settings — Redbooth</h1>

<%= form_for(@settings, url: redbooth_settings_path, method: :put) do |form| %>
  <div class="form-group half-spacer">
    <%= form.label :task_list_id, "Select Task List" %>
    <%= form.select :task_list_id, @task_lists, {}, class: "form-control"%>
  </div>
  <h3 class="spacer">Additional settings for automatically created tasks</h3>
  <div class="form-group half-spacer">
    <div class="radio">
      <label>
        <%= form.radio_button :task_private, true %>
        Tasks will be private
      </label>
    </div>
    <div class="radio">
      <label>
        <%= form.radio_button :task_private, false %>
        Tasks will be public
      </label>
    </div>
  </div>
  <div class="form-group half-spacer">
    <%= form.label :task_list_id, "Tasks description" %>
    <%= form.text_field :task_description, class: "form-control" %>
  </div>
  <%= submit_tag "Save changes", class: "spacer btn btn-primary" %>
<% end -%>

app/views/fetchr_status/show.html.erb
<div class="jumbotron">
  <h1><%= @manager.fetchr_status %></h1>
</div>

<h2><i class="fa fa-twitter"></i>&nbsp;Twitter Account Status</h2>
<div class="well">
  <p><%= @manager.twitter_status %></p>
  <p>
    <%= button_to @manager.twitter_action_text, "/auth/twitter/", method: "get", class: "btn btn-default" %>
  </p>
</div>

<h2>Adapters' State</h2>
<div class="well">
  <p><strong>Redbooth</strong></p>
  <p><%= @manager.redbooth_status %></p>
  <% if @manager.redbooth_connected? %>
    <p><%= button_to "Configure", edit_redbooth_settings_path,  method: "get", class: "btn btn-default" %></p>
  <% end %>
  <p>
    <%= button_to @manager.redbooth_action_text, "/auth/redbooth/", method: "get", class: "btn btn-default" %>
  </p>

</div>

<% if @manager.ready_to_start? %>
  <div class="btn-group">
    <%= link_to "Start", start_fetchr_path, method: "post", class: "btn btn-primary" %>
    <%= link_to "Import all previous and Start", import_and_start_fetchr_path, method: "post", class: "btn btn-warning" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TaskWatchr" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <a class="navbar-brand" href="/">TaskWatchr</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Reset everything", reset_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>